from enum import Enum


class FIELD_TYPE(Enum):
    TEXT_FIELD = 'TEXT_FIELD'
    NUMBER_FIELD = 'NUMBER_FIELD'
    DATE_FIELD = 'DATE_FIELD'
    DROPDOWN_FIELD = 'DROPDOWN_FIELD'
    CHECKBOX_FIELD = 'CHECKBOX_FIELD'