from enum import Enum


class INFORMATION_FIELD_TYPE(Enum):
    TEXT_INFORMATION_FIELD = 'TEXT_INFORMATION_FIELD'
    MAP_INFORMATION_FIELD = 'MAP_INFORMATION_FIELD'
    IMAGE_INFORMATION_FIELD = 'IMAGE_INFORMATION_FIELD'
